SET ARRAYSIZE 500
SET FLUSH OFF
SET LINESIZE 32767
SET PAGESIZE 0
SET SERVEROUTPUT OFF
SET FEEDBACK OFF
SET TERMOUT OFF
SET TRIMSPOOL ON
SET VERIFY OFF
SET HEADING ON
SET UNDERLINE OFF

ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'; 

SPOOL ./sql/get_&1..sql

prompt SET ARRAYSIZE 500
prompt SET FLUSH OFF
prompt SET LINESIZE 32767
prompt SET PAGESIZE 0
prompt SET SERVEROUTPUT OFF
prompt SET FEEDBACK OFF
prompt SET TERMOUT OFF
prompt SET TRIMSPOOL ON
prompt SET VERIFY OFF
prompt SET HEADING ON
prompt SET UNDERLINE OFF
prompt ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'; 
prompt 
prompt spool ./csv/&1..csv

--列名表示
SELECT
  DECODE(COLUMN_ID, '1', 'SELECT ', ' || '','' || '),
  '''' || COLUMN_NAME || ''''
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = UPPER('&1')
ORDER BY COLUMN_ID;
SELECT 'FROM DUAL;' FROM DUAL;

--データ取得、値はダブルクォーテーションで囲む
SELECT
  DECODE(COLUMN_ID, '1', 'SELECT  /*+ parallel(tbl 6) */', ' || '','' || '),
  '''"'' || ' || 'REPLACE(REPLACE(REPLACE(' || COLUMN_NAME || ', ''"'', ''''), CHR(13), '' ''), CHR(10), '' '')' || ' || ''"'''
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = UPPER('&1')
ORDER BY COLUMN_ID;

SELECT 'FROM ' || UPPER('&1') FROM DUAL;
SELECT 'WHERE 1=1;' FROM DUAL;

prompt spool off
prompt quit
SPOOL OFF
QUIT

